// <auto-generated />
using System;
using MeasurementApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeasureAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250426144644_ChangedPatientIdModel")]
    partial class ChangedPatientIdModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("MeasurementApi.Models.MeasurementRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeasurementSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeasurementTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementSessionId");

                    b.HasIndex("MeasurementTypeId");

                    b.ToTable("MeasurementRequests");
                });

            modelBuilder.Entity("MeasurementApi.Models.MeasurementSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PatientId");

                    b.ToTable("MeasurementSessions");
                });

            modelBuilder.Entity("MeasurementApi.Models.MeasurementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MeasurementTypes");
                });

            modelBuilder.Entity("MeasurementApi.Models.MeasurementValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeasurementRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("MeasurementValues");
                });

            modelBuilder.Entity("MeasurementApi.Models.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MeasurementApi.Models.SetupCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Used")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SetupCodes");
                });

            modelBuilder.Entity("MeasurementApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MeasurementApi.Models.MeasurementRequest", b =>
                {
                    b.HasOne("MeasurementApi.Models.MeasurementSession", "MeasurementSession")
                        .WithMany("MeasurementRequests")
                        .HasForeignKey("MeasurementSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeasurementApi.Models.MeasurementType", "MeasurementType")
                        .WithMany()
                        .HasForeignKey("MeasurementTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementSession");

                    b.Navigation("MeasurementType");
                });

            modelBuilder.Entity("MeasurementApi.Models.MeasurementSession", b =>
                {
                    b.HasOne("MeasurementApi.Models.User", "CreatedByUser")
                        .WithMany("CreatedMeasurementSessions")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeasurementApi.Models.Patient", "Patient")
                        .WithMany("MeasurementSessions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MeasurementApi.Models.MeasurementValue", b =>
                {
                    b.HasOne("MeasurementApi.Models.MeasurementRequest", "MeasurementRequest")
                        .WithMany("MeasurementValues")
                        .HasForeignKey("MeasurementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeasurementApi.Models.User", null)
                        .WithMany("SubmittedMeasurementValues")
                        .HasForeignKey("UserId");

                    b.Navigation("MeasurementRequest");
                });

            modelBuilder.Entity("MeasurementApi.Models.MeasurementRequest", b =>
                {
                    b.Navigation("MeasurementValues");
                });

            modelBuilder.Entity("MeasurementApi.Models.MeasurementSession", b =>
                {
                    b.Navigation("MeasurementRequests");
                });

            modelBuilder.Entity("MeasurementApi.Models.Patient", b =>
                {
                    b.Navigation("MeasurementSessions");
                });

            modelBuilder.Entity("MeasurementApi.Models.User", b =>
                {
                    b.Navigation("CreatedMeasurementSessions");

                    b.Navigation("SubmittedMeasurementValues");
                });
#pragma warning restore 612, 618
        }
    }
}
