// <auto-generated />
using System;
using MeasurementApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeasureAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250416145710_AddMeasurementTables")]
    partial class AddMeasurementTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("MeasurementApi.Models.MeasurementRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeasurementTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementTypeId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("MeasurementRequests");
                });

            modelBuilder.Entity("MeasurementApi.Models.MeasurementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MeasurementTypes");
                });

            modelBuilder.Entity("MeasurementApi.Models.MeasurementValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeasurementRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeasurementTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementRequestId");

                    b.HasIndex("MeasurementTypeId");

                    b.HasIndex("PatientId");

                    b.ToTable("MeasurementValues");
                });

            modelBuilder.Entity("MeasurementApi.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MeasurementApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MeasurementApi.Models.MeasurementRequest", b =>
                {
                    b.HasOne("MeasurementApi.Models.MeasurementType", "MeasurementType")
                        .WithMany()
                        .HasForeignKey("MeasurementTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeasurementApi.Models.Patient", "Patient")
                        .WithMany("MeasurementRequests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeasurementApi.Models.User", "RequestedByUser")
                        .WithMany("MeasurementRequests")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementType");

                    b.Navigation("Patient");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("MeasurementApi.Models.MeasurementValue", b =>
                {
                    b.HasOne("MeasurementApi.Models.MeasurementRequest", "MeasurementRequest")
                        .WithMany("MeasurementValues")
                        .HasForeignKey("MeasurementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeasurementApi.Models.MeasurementType", "MeasurementType")
                        .WithMany()
                        .HasForeignKey("MeasurementTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeasurementApi.Models.Patient", "Patient")
                        .WithMany("MeasurementValues")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementRequest");

                    b.Navigation("MeasurementType");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MeasurementApi.Models.MeasurementRequest", b =>
                {
                    b.Navigation("MeasurementValues");
                });

            modelBuilder.Entity("MeasurementApi.Models.Patient", b =>
                {
                    b.Navigation("MeasurementRequests");

                    b.Navigation("MeasurementValues");
                });

            modelBuilder.Entity("MeasurementApi.Models.User", b =>
                {
                    b.Navigation("MeasurementRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
